project:
  type: website
  output-dir: docs

website:
  title: "Lucas França, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - posts.qmd
      - about.qmd

format:
  html:
    theme:
      light: theme-light.scss
      dark: theme-dark.scss
    css: styles.css
    toc: true
    page-layout: full

