[build]
  publish = "docs"
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.555/quarto-1.4.555-linux-amd64.tar.gz
    tar -xzf quarto-1.4.555-linux-amd64.tar.gz
    export PATH=$PATH:$PWD/quarto-1.4.555/bin
    quarto render
  """

[build.environment]
  QUARTO_VERSION = "1.4.555"
