---
title: "Publications"
toc: true
---

{{< fa newspaper >}}: Article | 
{{< fa book >}}: Book/Book Chapter | 
{{< fa scroll >}}: Preprint | 
{{< fa chalkboard-user >}}: Conference Abstract

## 2026

{{< fa scroll >}} Diogo, F. M. C., **França, L. G. S.**, Leocadio-Miguel, M. A., Barbosa, M. N., & Azevedo, C. V. M. D. (2026). [Menstrual cycle irregularity is a biological determinant of mental health independent of sleep in adolescents](https://researchportal.northumbria.ac.uk/en/publications/menstrual-cycle-irregularity-is-a-biological-determinant-of-menta/). bioRxiv. (Submitted)

{{< fa newspaper >}} Whelan, T. P., **França, L. G. S.**, Dimitrov, M., Pretzsch, C. M., Velthuis, H., Pereira, A. C., ... & McAlonan, G. M. (2026). [Autistic Neural 'Shiftability': The Distinct Pharmacological Landscape of the Autistic Brain](https://researchportal.northumbria.ac.uk/en/publications/autistic-neural-shiftability-the-distinct-pharmacological-landsca-2/). Translational Psychiatry. (Accepted/In press)

{{< fa scroll >}} Smith, B. C., Pansara, Z., Timmerman, R. H., Molefi, E., Da Silva Costa, T., Thornton, C., **França, L. G. S.**, Stirling, R. E., Heaps, S. E., Karoly, P. J., Leocadio-Miguel, M., Taylor, P. N., Leiberg, K., & Wang, Y. (2026). [Habitual lifestyle timing explains circadian timing, but daily lifestyle changes do not, in free-living humans across 2000 days](https://arxiv.org/abs/2606.28261). arXiv:2606.28261.

{{< fa newspaper >}} Pugliane, K. C., **França, L. G. S.**, Leocadio-Miguel, M., & Araújo, J. F. (2026). [Low-latitude environmental regularity supports circadian organisation in blind adults](https://doi.org/10.1080/07420528.2026.2688906). Chronobiology International, 1-18.

{{< fa newspaper >}} dos Santos Batista, E., Silva Gomes, S. R. B., de Morais Ferreira, A. B., **França, L. G. S.**, Araújo, J. F., Mortatti, A. L., & Leocadio-Miguel, M. A. (2026). [From movement to METs: A validation of ActTrust® for energy expenditure estimation and physical activity classification in young adults](https://doi.org/10.1371/journal.pone.0348631). PLoS One, 21(5), e0348631.

{{< fa scroll >}} Pugliane, K. C., **Franca, L. G. S.**, Leocadio-Miguel, M., & Araújo, J. F. (2026). [Low-latitude environmental regularity sustains non-photic entrainment in blind adults](https://doi.org/10.64898/2026.03.19.712663). bioRxiv.

{{< fa newspaper >}} Dimitrov, M., Wong, N. M. L., Leaman, S., **França, L. G. S.**, Valasakis, I., He, J., ... & Daly, E. (2026). [μ-Opioid Modulation of Sensorimotor Functional Connectivity in Autism: Insights from a Pharmacological Neuroimaging Investigation using Tianeptine](https://doi.org/10.1016/j.bpsgos.2025.100663). Biological Psychiatry Global Open Science, 6(2), 100663.

{{< fa newspaper >}} Cupertino, L., Lirani-Silva, E., Orcioli-Silva, D., Beretta, V. S., **França, L. G. S.**, Coelho, D. B., & Vitorio, R. (2026). [From Resting-State to Movement: The Role of Cortical Networks in Parkinsonian Gait](https://doi.org/10.1016/j.gaitpost.2025.08.079). Gait and Posture, 125, 109961.

## 2025

{{< fa newspaper >}} Lirani-Silva, E., Silva, L. C. S., Orcioli-Silva, D., Beretta, V. S., **Franca, L. G. S.**, Coelho, D. B., & Vitorio, R. (2025). [Resting-state Alpha Reactivity Is Reduced in Parkinson's Disease and Associated With Gait Variability](https://doi.org/10.1177/15459683251347631). Neurorehabilitation and Neural Repair, 39(9), 742-751.

{{< fa scroll >}} dos Santos Batista, E., Basilio Gomes, S. R., de Morais Ferreira, A. B., **Franca, L. G. S.**, Fontenele Araújo, J., Mortatti, A. L., & Leocadio-Miguel, M. A. (2025). [From Movement to METs: A Validation of ActTrust® for Energy Expenditure Estimation and Physical Activity Classification in Young Adults](https://doi.org/10.1101/2025.05.16.654458). bioRxiv.

{{< fa scroll >}} Dimitrov, M., Wong, N. M. L., Leaman, S., **Franca, L. G. S.**, Valasakis, I., He, J., ... & Daly, E. (2025). [μ-Opioid Modulation of Sensorimotor Functional Connectivity in Autism: Insights from a Pharmacological Neuroimaging Investigation using Tianeptine](https://doi.org/10.1101/2025.03.12.25323848). bioRxiv.

{{< fa newspaper >}} Kulgod, A., van der Linden, D., **Franca, L.**, Jackson, M., & Zamansky, A. (2025). [Non-invasive canine electroencephalography (EEG): a systematic review](https://doi.org/10.1186/s12917-025-04523-3). BMC Veterinary Research, 21(1), 73.

{{< fa chalkboard-user >}} Whelan, T. P., **Franca, L. G. S.**, Dimitrov, M., Mulcrone, N., Puts, N. A. J., Daly, E., & McAlonan, G. M. (2025). [The pharmacologically diverse human brain: how neurosignalling systems regulate neurotypical and neurodivergent resting-state networks](https://doi.org/10.1093/ijnp/pyae059.460). International Journal of Neuropsychopharmacology, 28(Supplement_1), i261.

## 2024

{{< fa scroll >}} Lirani-Silva, E., Silva, L. C. S., Orcioli-Silva, D., Beretta, V. S., **Franca, L. G. S.**, Coelho, D. B., & Vitorio, R. (2024). [Resting-state alpha reactivity is reduced in Parkinson disease and associated with gait variability](https://doi.org/10.1101/2024.11.27.625690). bioRxiv.

{{< fa scroll >}} Whelan, T. P., **Franca, L. G. S.**, Dimitrov, M., Pretzsch, C. M., Velthuis, H., Pereira, A. C., ... & McAlonan, G. M. (2024). [Autistic Neural Shiftability: The Distinct Pharmacological Landscape of the Autistic Brain](https://doi.org/10.1101/2024.11.08.24316969). medRxiv.

{{< fa newspaper >}} Ferré, I. B. S., Corso, G., Lima, G. Z. S., Lopes, S. G., Leocadio-Miguel, M. A., **França, L. G. S.**, Prado, T. L., & Araújo, J. F. (2024). [Cycling reduces the entropy of neuronal activity in the human adult cortex](https://doi.org/10.1101/2024.01.31.578253). PLoS One.

{{< fa newspaper >}} Gale-Grant, O., Chew, A., Falconer, S., **França, L. G. S.**, Fenn-Moltu, S., Hadaya, L., ... & Batalle, D. (2024). [Clinical, socio-demographic, and parental correlates of early autism traits](https://doi.org/10.1101/2022.09.26.508121). Scientific Reports 14, 8393.

{{< fa newspaper >}} **França, L. G. S.**, Ciarrusta, J., Gale-Grant, O., Fenn-Moltu, S., Fitzgibbon, S., Chew, A., ... & Batalle, D. (2024). [Neonatal brain dynamic functional connectivity in term and preterm infants and its association with early childhood neurodevelopment](https://doi.org/10.1038/s41467-023-44050-z). Nature Communications. 15, 16.

{{< fa scroll >}} Ferré, I. B. S., Corso, G., Lima, G. Z. S., Lopes, S. G., Leocadio-Miguel, M. A., **França, L. G. S.**, Prado, T. L., & Araújo, J. F. (2024). [Cycling reduces the entropy of neuronal activity in the human adult cortex](https://doi.org/10.1101/2024.01.31.578253). bioRxiv, 2024.01.31.578253.

## 2023

{{< fa book >}} **França, L. G. S.**, Fenn-Moltu, S., & Batalle, D. (2023). [Dynamic functional connectivity](https://doi.org/10.1016/B978-0-323-85280-7.00006-3). In Connectome Analysis (pp. 219-245). Academic Press.

{{< fa scroll >}} Kulgod, A., Linden, D. V. D., **Franca, L. G. S.**, Jackson, M., & Zamansky, A. (2023). [Non-invasive canine electroencephalography (EEG): a systematic review](https://doi.org/10.1101/2023.08.14.552730). bioRxiv, 2023-08.

## 2022

{{< fa scroll >}} **França, L. G. S.**, Ciarrusta, J., Gale-Grant, O., Fenn-Moltu, S., Fitzgibbon, S., Chew, A., ... & Batalle, D. (2022). [Neonatal brain dynamic functional connectivity: impact of preterm birth and association with early childhood neurodevelopment](https://doi.org/10.1101/2022.11.16.516610). bioRxiv, 2022-11.

{{< fa scroll >}} Gale-Grant, O., Chew, A., Falconer, S., **França, L. G. S.**, Fenn-Moltu, S., Hadaya, L., ... & Batalle, D. (2022). [Clinical, socio-demographic, and parental correlates of early autism traits](https://doi.org/10.1101/2022.09.26.508121). bioRxiv, 2022-09.

{{< fa newspaper >}} Gale‐Grant, O., Fenn‐Moltu, S., **França, L. G. S.**, Dimitrova, R., Christiaens, D., Cordero‐Grande, L., ... & Batalle, D. (2022). [Effects of gestational age at birth on perinatal structural brain development in healthy term‐born babies](https://doi.org/10.1002/hbm.25743). Human Brain Mapping, 43(5), 1577-1589.

{{< fa newspaper >}} Kendall, C., Kerr, L. R. F. S., Miranda, J. G. V., Rubin de Pinho, S. T., Silva Andrade, R. F., Rodrigues, L. C.,..., **França, L. G. S.**, ... & Barreto, M. L. (2022). [A social network approach for the study of leprosy transmission beyond the household](https://doi.org/10.1093/trstmh/trab071). Transactions of the Royal Society of Tropical Medicine and Hygiene, 116(2), 100-107.

## 2019

{{< fa newspaper >}} Vakharia, V. N., Sparks, R. E., Li, K., O'Keeffe, A. G., Pérez‐García, F., **França, L. G. S.**, ... & Duncan, J. S. (2019). [Multicenter validation of automated trajectories for selective laser amygdalohippocampectomy](https://doi.org/10.1111/epi.16307). Epilepsia, 60(9), 1949-1959.

{{< fa newspaper >}} Li, K., Vakharia, V. N., Sparks, R., **França, L. G. S.**, Granados, A., McEvoy, A. W., ... & Duncan, J. S. (2019). [Optimizing trajectories for cranial laser interstitial thermal therapy using computer-assisted planning: a machine learning approach](https://doi.org/10.1007/s13311-018-00693-1). Neurotherapeutics, 16, 182-191.

{{< fa newspaper >}} **França, L. G. S.**, Montoya, P., & Miranda, J. G. V. (2019). [On multifractals: a non-linear study of actigraphy data](https://doi.org/10.1016/j.physa.2018.09.122). Physica A: Statistical Mechanics and its Applications, 514, 612-619.

## 2018

{{< fa newspaper >}} **França, L. G. S.**, Miranda, J. G. V., Leite, M., Sharma, N. K., Walker, M. C., Lemieux, L., & Wang, Y. (2018). [Fractal and multifractal properties of electrographic recordings of human brain activity: toward its use as a signal feature for machine learning in clinical applications](https://doi.org/10.3389/fphys.2018.01767). Frontiers in physiology, 9, 1767.

{{< fa scroll >}} **França, L. G. S.**, Miranda, J. G., Leite, M., Sharma, N. K., Walker, M. C., Lemieux, L., & Wang, Y. (2018). [Fractal and multifractal properties of electrographic recordings of human brain activity](https://doi.org/10.48550/arXiv.1806.03889). arXiv preprint arXiv:1806.03889.

## 2017

{{< fa newspaper >}} Sharma, N. K., Pedreira, C., Centeno, M., Chaudhary, U. J., Wehner, T., **França, L. G. S.**, ... & Lemieux, L. (2017). [A novel scheme for the validation of an automated classification method for epileptic spikes by comparison with multiple observers](https://doi.org/10.1016/j.clinph.2017.04.016). Clinical Neurophysiology, 128(7), 1246-1254.

{{< fa newspaper >}} Costa, I. D. S., Gamundí, A., Miranda, J. G. V., **França, L. G. S.**, De Santana, C. N., & Montoya, P. (2017). [Altered functional performance in patients with fibromyalgia](https://doi.org/10.3389/fnhum.2017.00014). Frontiers in human neuroscience, 11, 14.
